#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt-get update -y && \
sudo apt-get install -y nginx
if [ $? -eq 0 ]
then
    echo -e \
"http {
    server {
        listen 80;
        root /var/www/school;
    }
}
events {
}" > /etc/nginx/nginx.conf
    mkdir -p /var/www/school
    echo "Hello World!" > \
	/var/www/school/index.html
    service nginx start
    if [ $? -ne 0 ]
    then
	"Problem starting nginx"
	exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi
exit 0
