#!/usr/bin/env bash
#Badluck, Goodluck, BestSChool

counter=1

while [ $counter -le 20 ]
do
    if [ $counter -eq 4 ]
    then
        echo -e "4\nbad luck from china"
    elif [ $counter -eq 9 ]
    then
        echo -e "9\nbad luck from japan"
    elif [ $counter -eq 17 ]
    then
        echo -e "17\nbad luck from japan italy"
    else
        echo "Best School"
    fi
    (( counter++ ))
done
